version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  # Maintain dependencies for Devcontainers
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
  # Maintain dependencies for Container Images
  - package-ecosystem: docker
    directories:
      - /build/img
      - /build/*/img
    schedule:
      interval: weekly
