# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'docker' label to Dockerfile
docker:
  - build/package/Dockerfile
  - build/package/**/Dockerfile

# Add 'tooling' label to change within tools and .run
tooling:
  - tools/*
  - tools/*/**
