# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'patch' label to any patch file changes
patch:
  - "*.patch"

# Add 'docker' label to Dockerfile changes
docker:
  - build/package/Dockerfile
  - build/package/**/Dockerfile

# Add 'scripts' label to changes within scripts
scripts:
  - scripts/*
  - scripts/*/**
  - scripts/**/*

# Add 'tooling' label to changes within tools
tooling:
  - tools/*
  - tools/*/**
