# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'github-actions' label to any changes in the .github directory
github-actions:
  - .github/workflows/*
  - .github/workflows/*/**
  - .github/dependabot.yml
  - .github/dependabot.yml/**
  - build/package/action.yml
  - build/package/actions/**

# Add 'patch' label to any patch file changes
patch:
  - "*.patch"

# Add 'docker' label to Dockerfile changes
docker:
  - build/package/Dockerfile
  - build/package/**/Dockerfile

# Add 'scripts' label to changes within scripts
scripts:
  - scripts/*
  - scripts/*/**
  - scripts/**/*

# Add 'tools' label to changes within tools
tools:
  - tools/*
  - tools/*/**
