---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/config/crd/experimental
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd
