---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-gw-cert
  namespace: kube-system
spec:
  secretName: default-gw-tls
  dnsNames:
    - "*.devos.local"
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-ca-issuer
