---
images:
  compiler: ${arch}-linux-gnu-
  bootloader:
    targets:
      - qemu:arm:qemu_arm_defconfig
      - qemu:aarch64:qemu_arm64_defconfig
      - qemu:riscv64:qemu-riscv64_spl_defconfig
      - socfpga:arm:socfpga_de10_standard_defconfig
      - socfpga:aarch64:socfpga_agilex5_defconfig
  kernel: {}
  container:
    devcontainers: []
    languanges: []
    toolchains: []
    services: []
    custom: []
