name: Build Pipeline

on:
  push:
    paths:
      - build/img/**
      - build/scripts/init-devos.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false #${{ github.ref == 'refs/heads/main' }}
      matrix:
        container:
          - name: devcontainer
            repo: ghcr.io
            platform: linux/amd64,linux/arm64
          - name: kubernetes-entrypoint
            platform: linux/amd64,linux/arm64,linux/riscv64
            repo: docker.io
            path: sanselme
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build Container (ghcr.io)
        uses: anselmes/cicd/.github/actions/build@main # fixme: main https://github.com/anselmes/cicd/commit/main
        if: ${{ matrix.container.repo == 'ghcr.io' }}
        with:
          build-container-image: true
          container-image-file: build/img/${{ matrix.container.name }}/Dockerfile
          container-image-name: ${{ matrix.container.repo }}/${{ github.repository_owner }}/${{ matrix.container.name }}
          container-image-platforms: ${{ matrix.container.platform }}
          container-image-repo-password: ${{ secrets.GHCR_TOKEN }}
          container-image-repo-username: ${{ github.actor }}
          container-image-repo: ${{ matrix.container.repo }}
          push-container-image: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          container-image-tags: |
            type=raw,value=${{ matrix.container.tags || '24.04' }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          container-image-labels: |
            org.opencontainers.image.title=${{ matrix.container.name }}
            org.opencontainers.image.description=${{ matrix.container.description || matrix.container.name }}
            org.opencontainers.image.source=${{ github.repository }}

      - name: Build Container (docker.io)
        uses: anselmes/cicd/.github/actions/build@main # fixme: main https://github.com/anselmes/cicd/commit/main
        if: ${{ matrix.container.repo == 'docker.io' }}
        with:
          build-container-image: true
          container-image-file: build/img/${{ matrix.container.name }}/Dockerfile
          container-image-name: ${{ matrix.container.repo }}/${{ github.actor }}/${{ matrix.container.name }}
          container-image-platforms: ${{ matrix.container.platform }}
          container-image-repo-password: ${{ secrets.DOCKER_TOKEN }}
          container-image-repo-username: ${{ github.actor }}
          container-image-repo: ${{ matrix.container.repo }}
          push-container-image: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          container-image-tags: |
            type=raw,value=${{ matrix.container.tags || '24.04' }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=sha
          container-image-labels: |
            org.opencontainers.image.title=${{ matrix.container.name }}
            org.opencontainers.image.description=${{ matrix.container.description || matrix.container.name }}
            org.opencontainers.image.source=${{ github.repository }}
